name: Ian Kynnersley
title: Freelance CTO
description: Ian Kynnersley is a technical leader and startup CTO. He can be freelance, consulting, interim, advisory or permanent.
url: https://www.iankynnersley.co.uk
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
permalink: pretty
sass:
  style: compressed
# markdown: redcarpet
