name: Ian Kynnersley
title: Freelance CTO
description: Ian Kynnersley is a freelance technical leader and CTO
url: https://www.iankynnersley.co.uk
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
permalink: pretty
# markdown: redcarpet
