name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.7 # last version of 2.6.x
    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install
    - name: Build the site in the jekyll/builder container
      run: |
        bundle exec jekyll build
    - name: Deploy to S3
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # This ENV var apparently prevents the AWS sync error 255
        # https://github.com/actions/checkout/issues/440#issuecomment-854240996
        #
        # Alternatively, try specifying ubuntu-18.04 above
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws s3 sync _site/ s3://www.iankynnersley.co.uk
    - name: Cloudflare Purge Cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
